const FETCH_POKEMON = 'FETCH_POKEMON';
const UPDATE_POKEMON = 'UPDATE_POKEMON';
const FETCH_POKEMON_BY_ID = 'FETCH_POKEMON_BY_ID';
const UPDATE_CURRENT_POKEMON = 'UPDATE_CURRENT_POKEMON';

export {
  FETCH_POKEMON,
  UPDATE_POKEMON,
  FETCH_POKEMON_BY_ID,
  UPDATE_CURRENT_POKEMON
};

export default {
  FETCH_POKEMON,
  UPDATE_POKEMON,
  FETCH_POKEMON_BY_ID,
  UPDATE_CURRENT_POKEMON
};